import mongoose from "mongoose";

const userinfo = new mongoose.Schema(
    {
        userID:{
            type:String,
        },
        userName:{
            type:String,
        },
        education:[
            {
                userID:{
                    type:String,
                },
                university:{
                    type:String,
                    default:null
                },
                universityDtae:{
                    type:String,
                    default:null
                },
                UniversityStream:{
                    type:String,
                    default:null
                },
                UniversityCgpa:{
                    type:String,
                        default:null
                  },
                  educationimage:{
                    type:String,
                    default:null,
                }
            }
        ],
        skills:[
            {
                userID:{
                    type:String,
        
                },
                skillsTittle:{
                    type:String,
                    default:null
                },
                skilllevel:{
                    type:String,
                    default:null
                },
                skillrating:{
                    type:String,
                    default:null
                },
            }
        ],
        projects:[
            {
                userID:{
                    type:String,
                },
                projectTittle:{
                    type:String,
                    default:""
                },
                projectDesc:{
                    type:String,
                    default:""
                },
                projectlevel:{
                    type:String,
                    default:""
                },
                projectTechology:{
                    type:String,
                    default:""
                },
                projectlinks:{
                    type:String,
                    default:""
                },
                projectimage:{
                    type:String,
                    default:"assests/images/pro.png",
                
                }
            }
        ],
        certificate:[
            {
                uderID:{
                    type:String,
                },
                certificateimage:{
                    type:String,
                    default:null
                
                }
            }
        ],
        experiance:[{
            userID:{
                type:String
            },
            companyName:{
                type:String,
                default:null
            },
            YearTotal:{
                type:String,
                default:null,
            },
            workingField:{
                type:String,
                default:null
            },
            starting:{
                type:String,
                default:null,
            }
        }]
    },
    {timestamps:true}
);

export const userInfo = mongoose.model('userInfo', userinfo)